const IMAGES = {
    LOAD: 'IMAGES_LOAD',
    LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    LOAD_FAIL: 'IMAGES_LOAD_FAIL'
}

const AUTHOR = {
    LOAD: 'AUTHOR_LOAD',
    LOAD_SUCCESS: 'AUTHOR_LOAD_SUCCESS',
    LOAD_FAIL: 'AUTHOR_LOAD_FAIL'
}

export { IMAGES , AUTHOR };